# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Web

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
         flutter-version: '2.10.4'
         channel: 'stable'
         cache: true
      - name: Install dependencies
        run: dart pub get
      - run: flutter build web
      - run: |
         git clone -b gh_pages https://github.com/Itzbenz/itzcord.git gh_pages
         find gh_pages -mindepth 1 -not -regex "^\./\.git.*" -print0 | xargs -0 -I {} rm -rf {}
         mv build/web/* gh_pages
         cd gh_pages
         git add .
         git config --local user.email "github-actions[bot]@users.noreply.github.com"
         git config --local user.name "Bob Builder[Bot]"
         git commit -a "Cool"
         git push
